name: Build and deploy to gh-pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Deploy react to gh-pages
      uses: alainQtec/deploy-react-to-ghpages@1.0.0-beta.2
